version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          command: |
            git config user.email "test@example.com"
            git config user.name "CircleCI"
      - run:
          name: Setup
          command: |
            ./repo-setup.sh -n
      - run:
          name: AOSP Build
          command: ./build.sh
