version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run: export TERM=xterm
      - run:
          name: Setup
          command: |
            ./repo-setup.sh -n
      - run:
          name: AOSP Build
          command: ./build.sh
