version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          command: |
            sed -i 's#archive.ubuntu.com/ubuntu#ftp.heanet.ie/pub/ubuntu#g' /etc/apt/sources.list
            sed -i 's#security.ubuntu.com/ubuntu#ftp.heanet.ie/pub/ubuntu#g' /etc/apt/sources.list
            git config user.email "test@example.com"
            git config user.name "CircleCI"
      - run:
          name: Setup
          command: |
            ./repo-setup.sh -n
      - run:
          name: AOSP Build
          command: ./build.sh
